mindmap
  root((2.2 Making Marketing Decisions))
    Marketing mix
      Product
      Price
      Promotion
      Place
      Integrated decisions
    Product
      Design mix
        Function
        Aesthetics
        Cost
      Product life cycle
        Introduction
        Growth
        Maturity
        Decline
      Extension strategies
        Advertising
        Price reduction
        Added value
        New markets
        New packaging
      Differentiation
        USP
        Branding
        Legal protection
    Price
      Demand effect
      Profit margin effect
      Influences
        Objectives
        Competitors
        Customers
        Costs
        Life cycle
        Economy
        Legislation
    Promotion
      Aims
        Inform
        Persuade
        Remind
        Build brand
      Methods
        Advertising
        Sponsorship
        Sales promotion
        Social media
      Technology
        Online targeting
        Viral advertising
        Apps
        E-commerce
    Place
      Retailers
      Wholesalers
      Agents
      Direct selling
      E-tailers
      Channel choice
        Product nature
        Image
        Market spread
        Competition
        Business size
        Control
    Competitive advantage
      Better product
      Lower price
      Memorable promotion
      Convenient place
